name: Build check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install modules
        run: yarn
      - name: Build the package
        run: yarn build
